error_reporting = E_ERROR | E_WARNING | E_PARSE | E_NOTICE
display_errors = off
display_startup_errors = off
log_errors = on
error_log = /proc/self/fd/2
upload_max_filesize = 300M
memory_limit = 300M
post_max_size = 300M
max_execution_time = 900
max_input_vars = 100000
default_charset = UTF-8
client_max_body_size = 300M

[Date]
date.timezone = ${TZ}

[mbstring]
mbstring.language = Neutral

[xdebug]
xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.start_with_request = trigger
xdebug.log = /dev/null
