[program:granite-nginx]
process_name=%(program_name)s
command=/bin/sh -c "envsubst '\$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
autostart=true
autorestart=true
priority=6
redirect_stderr=true

